### ISSUE TITLE
Some additions for the chat

### ISSUE THREAD

**Issue by NorbiPeti** [TBMCPlugins/DiscordPlugin#12]
- [x] Make sendMessage async(!) - since commands are sync, it lags the server
- [x] Add player joined/left messages
- [x] (Look into what Essentials does for /eco)
- [x] Send death messages
- [x] Send attachment URLs to Minecraft
- [x] Remove color codes from command responses
- [x] Use one DiscordSender instance per user
- [x] Put [d] or [d|g] before messages sent from Discord
- [x] Make broadcasted messages only appear once
- [x] Send AFK messages
- [x] Fs (change every broadcasted message to actually use the broadcast method)
- [x] Finish PM support (@ChromaBot mcchat)
- [x] (Re-)Add support for channel identifiers on Discord (for PMs at least)
- [x] Add support for other MC chat channels in PMs
- [ ] Role color

**Comment by alisolarflare** [comment]
ooooooooo this is fancy

**Comment by NorbiPeti** [comment]
ikr
